alias rm='rm -i'
#alias ps='ps aux|grep -v ps|grep -v grep|more'
alias cl='clear'
alias x+='chmod +x'
alias x-='chmod -x'
alias w+='chmod +w'
alias w-='chmod -w'
alias cls='cl;ls'
alias h='history'
alias ..='cd ..'
alias la='ls -Al' # show hidden files
alias ls='ls -hF --color' # add colors for filetype recognition
alias scope="ssh dferone@ui.scope.unina.it"
alias n="nautilus . &"
alias t="thunar . &"
alias rimuoviLog="rm -fr $HOME/Dropbox/linux_files/logs/*"
alias ircpi="ssh pi@raspberrypi -t .irssi/screen"
alias Lavoro="cd $HOME/Dropbox/Lavoro"
alias Progetti="cd $HOME/Dropbox/Lavoro/Progetti/"
alias CNRProject="cd $HOME/Dropbox/Lavoro/Progetti/CNR"
alias CSPTPProject="cd $HOME/Dropbox/Lavoro/Progetti/CSPTP/Personale"
alias pCenter="cd $HOME/Dropbox/Lavoro/Progetti/p-Center/Antonio"
