alias rm='rm -i'
#alias ps='ps aux|grep -v ps|grep -v grep|more'
alias cl='clear'
alias x+='chmod +x'
alias x-='chmod -x'
alias w+='chmod +w'
alias w-='chmod -w'
alias cls='cl;ls'
alias h='history'
#alias ..='cd ..'
alias la='ls -Al' # show hidden files
alias ls='ls -hF --color' # add colors for filetype recognition
alias scope="ssh dferone@ui.scope.unina.it"
alias n="nautilus . &"
alias t="thunar . &"
alias rimuoviLog="find $HOME/Dropbox/linux_files/logs/ -mtime +5 -exec rm -f {} \;"
alias "cs=xclip -selection clipboard"
alias "vs=xclip -o -selection clipboard"
